@startuml ssd_us217
autonumber
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

actor "Maintenance Technician" as Actor
participant "System" as Sys

activate Actor
Actor -> Sys : searchMaintenanceRecords(component)
activate Sys
Sys --> Actor : 200 OK (Page<MaintenanceRecordResponse>)
deactivate Sys
deactivate Actor

@enduml
