@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys
Actor -> Sys : searchAircrafts(modelName?, status?, year?, feature?, pageable)
activate Sys
Sys --> Actor : returns a paginated list of matching aircraft
deactivate Sys
@enduml


