@startuml
autonumber
actor "ATCC / Backoffice Operator" as Actor
participant "System" as Sys

alt Update route details
    Actor -> Sys : updateRoute(origin, destination, updatedDetails)
    activate Sys
    Sys --> Actor : returns updated Route details
    deactivate Sys
else Deactivate route
    Actor -> Sys : deactivateRoute(origin, destination)
    activate Sys
    Sys --> Actor : returns deactivated Route details
    deactivate Sys
end
@enduml
