@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys
Actor -> Sys : registerAircraft(registrationNumber, modelName, manufacturingDate, seatCapacity, status, features)
activate Sys
Sys --> Actor : returns created aircraft details
deactivate Sys
@enduml


