@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys

Actor -> Sys : createRoute(originIataCode, destinationIataCode, estimatedFlightTime, minimumRange, minimumCapacity, createdBy)
activate Sys
Sys --> Actor : returns created Route details
deactivate Sys
@enduml