@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys
Actor -> Sys : updateAircraft(registrationNumber, UpdateAircraftRequest, If-Match)
activate Sys
Sys --> Actor : returns updated ViewAircraftDetailsResponse
deactivate Sys
@enduml
