@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys

alt View route details
    Actor -> Sys : getRouteDetails(origin, destination)
    activate Sys
    Sys --> Actor : returns Route details
    deactivate Sys
else View routes from airport
    Actor -> Sys : getRoutesFromAirport(iataCode)
    activate Sys
    Sys --> Actor : returns routes list
    deactivate Sys
end
@enduml
