@startuml ssd_us221
autonumber
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

actor "Maintenance Supervisor" as Actor
participant "System" as Sys

activate Actor
Actor -> Sys : getAverageTurnaroundByModel(modelName)
activate Sys
Sys --> Actor : 200 OK (AverageTurnaroundByModelResponse)
deactivate Sys
deactivate Actor

@enduml
