@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys

Actor -> Sys : getRouteHistory(origin, destination)
activate Sys
Sys --> Actor : returns route history list
deactivate Sys
@enduml