@startuml
left to right direction
skinparam packageStyle rectangle

actor "Backoffice Operator" as BO
actor "ATCC" as ATCC

rectangle "Flight Routes & Operations (WP #3A)" {
  usecase "US110 - Create a flight route" as UC110
  usecase "US111 - Keep track of route history" as UC111
  usecase "US112 - Update or deactivate a route" as UC112
  usecase "US113 - View routes from airport / details by ID" as UC113
  usecase "US114 - Search for routes" as UC114
}

ATCC --> UC110
ATCC --> UC111
ATCC --> UC112
ATCC --> UC113
ATCC --> UC114

BO --> UC112

@enduml