@startuml ssd_deleteAircraft
autonumber
skinparam monochrome true
skinparam packageStyle rect
skinparam shadowing false

actor "Backoffice Operator" as BO
participant "System" as Sys

activate BO
BO -> Sys : deleteAircraft(registration)
activate Sys
Sys --> BO : 204 No Content
deactivate Sys
deactivate BO

@enduml
