@startuml
autonumber
actor "ATCC" as Actor
participant "System" as Sys
Actor -> Sys : getOperationalHours(registrationNumber)
activate Sys
Sys --> Actor : returns operational hours
deactivate Sys
@enduml
